
== Using jgroups-raft


=== Cluster members and identity

每个集群成员都有一个由JGroups分配的地址（一个UUID）和一个需要由用户分配的`raft_id`,raft_id是一个字符串（例如“A”），它在整个集群中需要是唯一的。 换句话说，`raft_id`是
为jgroups-raft而成员的身份。

Raft集群具有固定的大小，因此可以为领导者选举以及条目追加。 允许进入群集的成员在`RAFT.members`中定义，例如，

[source,xml]
----
<raft.RAFT members="A,B,C" raft_id="${raft_id:undefined}"/>
----

这定义了3个成员的集群：“A”，“B”和“C”（其大多数为2）。

这些是3个成员的`raft_id`属性，所以上例中的`raft_id`属性需要是其中的一个。
如果我们不使用系统属性`-Draft_id = X`（其中X需要为“A”，“B”或“C”）启动此成员，那么该成员将启动为“未定义”: 不是“{”A“，”B“，”C“}`的成员。

注：请注意，尽管`RAFT`确保非成员不能加入群集，`NO_DUPES`协议确保没有重复的成员可以加入。 例如：如果我们有`RAFT.members =“A，B，C”`和实际成员“A”和“B”加入，
那么重复名称为“B”的成员的加入尝试将被拒绝，该成员无法加入集群。
属性`raft_id`也被用来定义持久化日志的位置; 除非在“RAFT”中定义了`log_name`，否则该位置被计算为例如`<temp_dir> / <raft_id> .log`。`/ TMP / A.log`。

请注意，可以动态添加和删除成员（无需关闭整个群集，更改配置并重新启动它），请参阅<DynamicMembership>。

=== RaftHandle

如“ArchitectureFig”所示，“RaftHandle”是用户将要处理的主要类。 它提供了更改复制状态机中状态（追加条目）的方法，并且可以向其注册状态机。 状态机将在启动时初始化，并在每次更改时由jgroups-raft更新。
一个成功的更改将致力于所有集群成员的持久日志并应用于其状态机，因此所有状态机都具有完全相同的状态。

==== Creation
RaftHandle的一个实例与_one_ JGroups通道关联，可以按如下方式创建：

[source,java]
----
JChannel ch=new JChannel("/home/bela/raft.xml"); // <1>
RaftHandle handle=new RaftHandle(ch, this);      // <2>
ch.connect("raft-cluster");                      // <3>
----
<1>创建新的JGroups频道（有关JGroups API的详细信息，请参阅JGroups手册）
<2>通过通道创建一个RaftHandle实例（它必须是非空的）。 第二个参数是`StateMachine`的一个实现。 如果为null，则不会更新变化的状态。 状态机可以用`stateMachine（StateMachine sm）`来设置。
<3>通道已连接，成员加入群集

==== Making changes
`setX（）`方法可用于进行更改：

[source,java]
----
byte[] set(byte[] buf, int offset, int length) throws Exception; // <1>
byte[] set(byte[] buf, int offset, int length, long timeout, TimeUnit unit) throws Exception; // <2>
CompletableFuture<byte[]> setAsync(byte[] buf, int offset, int length); // <3>
----
<1>同步改变; 调用者将被阻塞，直到更改已转发给领导者，领导者将其发送给所有将其应用于其持久日志的集群成员，并将变更回复给领导者。
 一旦领导者获得大部分ack，它就会将更改提交给自己的日志，将其应用到其状态机并将响应返回给调用者。 状态机因此只包含_committed changes_。
<2>和上面一样，只是这个调用有一个超时限制。 如果在收到大多数答案之前已经过去，则会抛出“TimeoutException”。
<3>异步改变; 这个方法立即返回一个`CompletableFuture`，它可以用来稍后检索结果，或者提供一些结果可用时执行的代码（例如`whenComplete（）`）。

请求和响应缓冲区的内容是特定于应用程序的。

例如，如果我们实现了一个可复值的HashMap，那么请求可能是`put（key，value）`。 `put（）`必须被序列化到缓冲区中，包括键和值。

当提交更改时，每个状态机需要将缓冲区反序列化为“put（key，value）”并将其应用于其状态（请参阅<< ImplementingStateMachine >>）。
如果有`put（）`调用的返回值，例如 与`key`关联的前一个值，那么它将被序列化到一个缓冲区并作为`setX（）`调用的结果返回。

[[ImplementingStateMachine]]
==== Implementing a StateMachine

`StateMachine`是一个接口，定义如下：

[source,java]
----
public interface StateMachine {
    byte[] apply(byte[] data, int offset, int length) throws Exception;  // <1>
    void   readContentFrom(DataInput in) throws Exception;               // <2>
    void   writeContentTo(DataOutput out) throws Exception;              // <3>
}
----
<1>只要日志条目是_committed_，就会调用此方法。 缓冲区的内容是特定于应用程序的（例如，如上所述，这可能是一个序列化的'put（key，value）'。
如果有一个将更改应用于状态机的返回值，则需要对其进行序列化，以便它可以 返回给调用者（例如客户端）。

<2>当'RAFT'需要从_snapshot_（状态机内容转储到外部流（例如文件））初始化状态机时调用此方法。
下面的`writeContentTo（）`方法在应用程序特定的格式之前将内容写到文件中，并且此方法现在需要将内容读回到状态机中。

<3>此方法与readContentFrom（）相反，并将此状态机的内容写入流（例如文件）。

[[Snapshots]]
==== Snapshotting and state transfer

所有集群成员都维护一个持久化日志，并将所有更改作为日志条目附加到日志末尾。 为防止日志无限增长，可以创建状态机的_snapshot_并截断日志。
这是用编程方式调用``snapshot（）`方法来完成的，或者是声明式的（见下文）。

此方法调用`StateMachine.writeContentTo（）`将状态机的状态转储到快照文件中，然后截断日志。 尚未创建日志的新成员通过首先向其发送快照来进行初始化。
之后，他们将通过常规的Raft机制迎头赶上。

通过将“RAFT.max_log_size”设置为日志允许增长的最大字节数,当到达该值时，将自动创建快照。

==== Miscellaneous methods

Other methods in `RaftHandle` include:

leader():: 返回当前Raft领导者的地址;如果没有领导者，则返回null（例如，如果没有选举领导者的多数票）
isLeader():: 目前的成员是否是领导者
addRoleListener(RAFT.RoleChange listener):: 允许注册一个'RoleChange`侦听器，当当前成员改变它的角色时（`Leader`，`Follower`，`Candidate`）,将会侦听
currentTerm():: 返回当前term
lastApplied():: 返回附加到日志的最后一个日志条目的索引
commitIndex():: 返回提交的最后一个日志条目的索引
raft()::返回当前成员堆栈中对“RAFT”协议的引用。 为需要直接访问“RAFT”的专家提供。

raftId(String id):: 用于以编程方式设置`raft_id`（注意，这也可以通过在XML配置中在`RAFT`中设置`raft_id`来完成。例如，以下代码在命令行中设置`raft_id`：
[source,java]
----
protected void start(String raft_id) throws Exception {
    JChannel ch=new JChannel("raft.xml").name(raft_id);   // <2>
    RaftHandle handle=new RaftHandle(ch, this).raftId(raft_id); // <3>
    ch.connect("raft-cluster");  // <4>
}

public static void main(String[] args) throws Exception {
    new bla().start(args[0]);  // <1>
}
----
<1>`raft_id`可以作为参数传递给程序
<2>通道已创建，其逻辑名称与“raft_id”相同。 这不是必需的，但方便。
<3>现在`raft_id`可以通过`RaftHandle.raftId（String id）`来设置。

=== Configuration

成员的配置可以通过XML配置文件或编程方式声明式完成。 有关详细信息，请参阅JGroups文档。
示例XML配置文件如下所示（为简洁起见进行了编辑）：

[source,xml]
----
<config xmlns="urn:org:jgroups"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
    <UDP
         mcast_addr="228.5.5.5"
         mcast_port="${jgroups.udp.mcast_port:45588}"/>
    <PING />
    <MERGE3 />
    <FD_SOCK/>
    <FD_ALL/>
    <VERIFY_SUSPECT timeout="1500"  />
    <pbcast.NAKACK2 xmit_interval="500"
                    discard_delivered_msgs="true"/>
    <UNICAST3 xmit_interval="500"
              max_msg_batch_size="500"/>
    <pbcast.STABLE desired_avg_gossip="50000"
                   max_bytes="4M"/>
    <raft.NO_DUPES/>                                                         // <1>
    <pbcast.GMS print_local_addr="true" join_timeout="2000"
                view_bundling="true"/>
    <UFC max_credits="2M" min_threshold="0.4"/>
    <MFC max_credits="2M" min_threshold="0.4"/>
    <FRAG2 frag_size="60K"  />
    <raft.ELECTION election_min_interval="100" election_max_interval="500"/> // <2>
    <raft.RAFT members="A,B,C,D" raft_id="${raft_id:undefined}"/>            // <3>
    <raft.REDIRECT/>                                                         // <4>
    <raft.CLIENT bind_addr="0.0.0.0" />                                      // <5>
</config>
----
<1> `NO_DUPES`：检查加入新成员不会导致成员资格中的'raft_ids`重复。 如果可以的话，拒绝JOIN。 必须放置在`GMS`下面的某个地方
<2> `选举“：该协议实施领导选举。 它与“RAFT”相互独立，并且可能（并且可能在将来）被替换为不同的选举协议。
     属性`election_min_interval`和`election_max_interval`定义jgroups-raft选择随机选举超时的范围。

<3> RAFT：主要协议，实现日志追加和提交，处理状态机更新，快照等。
    属性`members`定义（固定）成员资格（当从持久性日志初始化成员时，可能仍由`addServer` /`removeServer`日志条目重新定义）。
    属性`raft_id`定义当前成员的ID（如前所述，需要成为“成员”的一个要素）。
<4> REDIRECT用于将请求重定向到当前的Raft领导者，或者在没有成员领导的情况下抛出异常
<5> <CLIENT>侦听客户端请求的套接字（默认端口为“1965”），执行它们并将结果发回给client。 目前，已经实现了`addServer`和`removeServer`。

这是一个常规的JGroups XML配置，除了jgroups-raft添加了一些其他协议。

[[DynamicMembership]]
=== Adding and removing members dynamically

'RAFT'协议提供了addServer（String raft_id）和removeServer（String raft_id）方法来从静态成员（由RAFT.members定义）添加和删除服务器。
一次只能添加和移除一台服务器，添加或移除服务器需要提交大部分确认。

这两种方法都通过JMX公开，所以可以使用'jconsole'。 但是，jgroups-raft还提供了一个脚本（`client.sh`）以更方便的方式执行此操作。
该脚本使用`Client`连接到集群成员的1965端口(可以更改）。 该请求然后被转发给当前领导。

The steps to add a member are as follows (say we have `RAFT.members="A,B,C"` and want to add "D"):

* Call `bin/client.sh -add D`
** If needed, `-port PORT` or `-bind_addr ADDR` can be given, e.g. if we need to reach a member running on a different host
* Once `A` (the leader) processed `addServer("D")`, everybody's `RAFT.members` is `"A","B","C","D"`
* At this point, the XML configuration files should be updated so that `RAFT.members="A,B,C,D"`
* If not, members will read the correct membership when getting initialized by their logs
* A new member `D` can now be started (its XML config needs to have the correct `members` attribute !)





